### ISSUE TITLE
Project includes insecure guzzlehttp/guzzle as dependency

### ISSUE THREAD

**Issue by badjava** [deviantintegral/client_error_trace#9]
Note: The Drupal security team have made the determination that this issue can be fixed because there is no stable release of this project which is why this issue was created here.

As part of the httpoxy vulnerability, this module includes an affected version of guzzlehttp/guzzle package as a dependency:

http://cgit.drupalcode.org/client_error_trace/tree/composer.json?h=7.x-1.x#n13

The guzzlehttp/guzzle dependency should be updated to 6.2.1 to address this issue.

**Comment by deviantintegral** [comment]
I don't think this module is in use by anyone anymore, but I pushed up a completely untested update to Guzzle 6. We were only using the Url class, so it was pretty straight forward.
